version: 2.1

jobs:
    build:
        docker:
            - image: python:3.7.3-stretch
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "requirements.txt" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: install dependencies
                  command: |
                      python3 -m venv venv
                      . venv/bin/activate
                      make install
            - save_cache:
                  paths:
                      - ./venv
                  key: v1-dependencies-{{ checksum "requirements.txt" }}
            # run lint!
            - run:
                  name: run lint
                  command: |
                      . venv/bin/activate
                      make lint
                      
    push-image:
        docker:
            - image: python:3.7.3-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Push image to docker
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    ./run_docker.sh capstone
                    ./upload_docker.sh capstone $dockerUsername $dockerPassword

workflows:
    final:
        jobs:
            - build
            - push-image:
                  requires:
                      - build